### ISSUE TITLE
Remove `auto_escalate` option from ansible service broker

### ISSUE THREAD

**Issue by wtrocki** [aerogear/mobile-core#14]
## Description

 https://github.com/aerogear/mobile-core/pull/9 introduces new flag:
`auto_escalate`= true. We should not override this flag in long term. 

## Action

Remove `auto_escalate` option from ansible installer.

**Comment by camilamacedo86** [comment]
PR made : https://github.com/aerogear/mobile-core/pull/195

**Comment by camilamacedo86** [comment]
Closing it with the following info which was added in the PR:

"This is related with ansible broker trying to evaluate user permissions and in the past this caused issues on Mac environments, but since then this was fixed upstream. Ticket and PR could be closed."

"As for this issue, I think that this issue is outdated as we seen some problems with this on different docker versions and they are no longer valid."

More info: https://github.com/openshift/ansible-service-broker/blob/65cb73f6cb70fcfc1760e6266654889f856ff1d4/docs/deployment.md
