### ISSUE TITLE
Installer fails silently

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-core#204]
## Description

The installer runs, and can log into openshift console. However there is no mobile tab in service catalog despite waiting several minutes 

The issue is that no error was displayed

## Environment

*Operating system*:
Fedora 27

*OpenShift versions*: 
3.9

## Steps to reproduce
Ran installer accepting defaults, eg latest

**Comment by finp** [comment]
actual installer issue is reported at https://groups.google.com/d/topic/aerogear/oBhCnO9QmL8/discussion
(this issue was only raised to address the silent nature of install failure)

**Comment by camilamacedo86** [comment]
Hi @finp, could you run the command $oc version in order to get all details? Could you run the install with the param --debug and add here the full output for we check? Could you run the command $docker --version and add here the result?.

**Comment by camilamacedo86** [comment]
@finp it is since it did not occur in all versions and it can be some issue in some specific version of OCP, and or broker, and etc .. Could you provide this info?

**Comment by pmacko1** [comment]
@camilamacedo86 Hey Camila, I think I know what Paul wants to report:
I believe that the default behaviour of Ansible is that it reports a million unnecessary information as in:

![](https://user-images.githubusercontent.com/7708031/44155447-3cd1d032-a0a5-11e8-9c24-c9cfa234b3a5.png)

with warnings that do not really(???) mean anything, making it a scary UX. Downside of keeping Ansible's mouth shut is that you can't see errors as well.
I have very little understanding of this, so please correct me if I'm not correct. Thanks.

**Comment by camilamacedo86** [comment]
Hi @finp,

I create the issue https://github.com/aerogear/mobile-core/issues/205 for we solve the scenario where the installer finish with a success message, however, it faced an issue in the Ansible scripts. If this issue is about it could we move forward in favour of https://github.com/aerogear/mobile-core/issues/205 because of the description on there? 
 
Also, could you please re-run it with the --debug param for we check what issue are you facing and if it is the same reported on https://github.com/aerogear/mobile-core/issues/140 or not ? I'd like to check if it is another scenario that we could cover.

**Comment by finp** [comment]
@camilamacedo86  you've captured the issue perfectly in #205, closing
